name: Build and Release Go Binary

on:
  push:
    tags:
      - "v*"   # Trigger when pushing a tag like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5" # or your required version

      - name: Build
        run: go build -o book-app-image-processor ./main.go
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: book-app-image-processor
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
